### ISSUE TITLE
tx not found

### ISSUE THREAD

**Issue by raedah** [raedahgroup/blockbook#7]
This block

http://blockbook.raedahgroup.com:8080/block/00000000000000001e05ff6ea2a940fa0eca955e5036ebd50f545ee0364ebf99

shows this transaction but when clicked on

http://blockbook.raedahgroup.com:8080/tx/74f43a0b12cd14d3d87f07dccc9d3a50079676ae822cc2b9951772ab1d855636

it displays
Internal server error: Tx not found, data <nil>

**Comment by dmigwi** [comment]
Fixed by https://github.com/raedahgroup/blockbook/pull/11
